- name: nginx install and run 
  hosts: web 
  become: yes  # it takes sudo access
  tasks:
   - name: install nginx 
     ansible.builtin.package:  # ansible is heterogenous module that can work for all distros
      name: nginx 
      state: present