- name: variables to print 
  hosts: web 
  vars:   # play level, all tasks in theis play have access to this
   COURSE: "DevOps with AWS"
   DURATION: "120HRS"
   LEARNER: "maha lakshmi"
  tasks: 
  - name: print the information
    ansible.builtin.debug:
     msg: "Hi, my name is {{LEARNER}}, I am learning {{COURSE}} and it is {{DURATION}} a day"

  - name: print the information again
    vars:   # task level variable, overrides the play level
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, my name is {{LEARNER}}, I am learning {{COURSE}} and it is {{DURATION}} a day"

  - name: print the information again and again
    ansible.builtin.debug:
      msg: "Hi, my name is {{LEARNER}}, I am learning {{COURSE}} and it is {{DURATION}} a day"