- name: variables from files 
  hosts: web 
  vars_files:
  - vars.yaml
  tasks:
   - name: print the course information 
     ansible.builtin.debug:
      msg: "Hi, my name is {{LEARNER}}, I am learning {{COURSE}} and it is {{DURATION}} a day"