- name: variables from files 
  hosts: web 
  vars_prompt:
  - name: COURSE
    prompt: Enter the course name
  - name: LEARNER
    prompt: Enter the learner name
  - name: DURATION 
    prompt: Enter the duration of the course in hours
  tasks:
   - name: print the course information 
     ansible.builtin.debug:
      msg: "Hi, my name is {{LEARNER}}, I am learning {{COURSE}} and it is {{DURATION}} a day"