- name: variables from inventory 
  hosts: web 
  tasks: 
  - name: print variables
    ansible.builtin.debug:
     msg: "Hi, my name is {{LEARNER}}, I am learning {{COURSE}} and it is {{DURATION}} a day"

     # Ansible automatically go to inventory files and checks for variable declaration