- name: variables to print 
  hosts: web 
  vars:
   COURSE: "DevOps with AWS from PLAY level"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: COURSE
    prompt: Enter the course name
    private: false  # it means not confidential
  tasks: 
  - name: print variables
    vars:
      # COURSE: "DevOps with AWS from TASK level"
    ansible.builtin.debug:
     msg: "Hi, I am learning {{COURSE}}"


# 1. command line/args
# 2. Task level
# 3. Files