- name: packages installing 
  hosts: web
  become: yes
  tasks: 
  - name: install packages
    ansible.builtin.package:
     name:  "{{ item.name }}"  # item is a keyword 
     state:  "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'present' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'nginx', state: 'present' }
    - { name: 'httpd', state: 'absent' }
    