- name: demo on filters/functions 
  hosts: local 
  connection: local 
  tasks: 
  - name: print the default variable 
    ansible.builtin.debug:
      msg: "Hello {{ COURSE | default('Ansible') }}"   # course is undefined variable 