- name: command vs shell
  hosts: local 
  connection: local 
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt # shell- login to the server and execute the command inside 
    # command module - it just issues the command
