- name: create ec2 and r53 records 
  hosts: local 
  connection: local 
  vars: 
    subnet_id: subnet-057a823df234beef9  # copy the subnet_id from the instances in the networking
    sg_id: sg-0525227f8e227493c  # copy the security group id from the AWS security 
    ami_id: ami-09c813fb71547fc4f   # copy the ami imag eid from the AWS details 
    instances:
    - mysql 
    - backend
    - frontend
  tasks:
  - name: create ec2 instance 
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances    # to catch the total information and output - registers


  - name: print the output 
    ansible.builtin.debug:
      msg: "{{ ec2-instances }}"